### ISSUE TITLE
Attempt to index field 'anim'

### ISSUE THREAD

**Issue by deanhu2** [stepulak/CountryballGame#3]
Hey, since pulling from your master branch iv been having the following bug being printed:

AnimationObjectionContainer.lua:27: attempt to index field 'anim' (a nil value)

Iv been looking into where the nil value.

**Comment by stepulak** [comment]
Did you change anything there? Because it's working properly. And on the 27th line there is an "end" statement, it shouldn't crash right here...

**Comment by deanhu2** [comment]
Weirdly after clearing all files and cloning just from your master branch i still receive the error, except at line 26:

AnimationObjectionContainer.lua:26: attempt to index field 'anim' (a nil value)

Line 26:    obj.anim:update(deltaTime)

Instead of line 27. So its a vanilla branch with no modifications from the master...i'll continue to look into it.

**Comment by stepulak** [comment]
Show me whole stack trace if you can. Btw isn't it AnimationObjectContainer.lua instead of AnimationObjection*?

**Comment by deanhu2** [comment]
Here is the entire stack trace i'm receiving, just in case it helps the error occurs just after the load screen after clicking the campaign button:

Error

AnimationObjectContainer.lua:26: attempt to index field 'anim' (a nil value)

Traceback

AnimationObjectContainer.lua:26: in function 'updateAnimObjects'
World.lua:1812: in function 'update'
Gameplay.lua:277: in function 'update'
Game.lua:236: in function 'update'
Campaign.lua:273: in function 'update'
MainMenu.lua:335: in function 'update'
main.lua:197: in function 'update'
[C}: in function 'xpcall'

**Comment by stepulak** [comment]
Yeah, the campaign is not working at all. Because there is "none". What you've seen were just testing examples... I've changed the texture's names etc., so that's why its crashing right now.

**Comment by deanhu2** [comment]
ah right, well atleast its not a bug haha. Maybe we should implement a try-catch and custom message if the  levels are missing?

**Comment by stepulak** [comment]
They are either corrupted or missing. The mechanism is not necessary, because in the final version, there will be a proper functional campaign.
